origin: ${env:MMT_HOST, 'http://localhost:5173'}
headers:
  - Access-Control-Allow-Origin
  - Access-Control-Allow-Credentials
  - Access-Control-Request-Headers
  - Access-Control-Request-Methods
  - Authorization
  - Origin
  - User-Agent
allowCredentials: true
