earthdata:
  # Endpoints for Earthdata.  These must remain in sync, because for instance ECHO SIT can't accept tokens from URS ops
  ops:
    urs_root: "https://urs.earthdata.nasa.gov"
    echo_root: "https://cmr.earthdata.nasa.gov/legacy-services"
    cmr_root: "https://cmr.earthdata.nasa.gov"
    edsc_root: "https://search.earthdata.nasa.gov"
    launchpad_root: "https://apps.launchpad.nasa.gov"
    launchpad_sbx_root: "https://apps.launchpad-sbx.nasa.gov"
    # uvg_root: "https://uvg.earthdata.nasa.gov"
    dmmt_root: "https://draftmmt.earthdata.nasa.gov"
    gkr_root: "https://gcmd.nasa-impact.net"
  uat:
    urs_root: "https://uat.urs.earthdata.nasa.gov"
    echo_root: "https://cmr.uat.earthdata.nasa.gov/legacy-services"
    cmr_root: "https://cmr.uat.earthdata.nasa.gov"
    edsc_root: "https://search.uat.earthdata.nasa.gov"
    launchpad_root: "https://apps.launchpad.nasa.gov"
    launchpad_sbx_root: "https://apps.launchpad-sbx.nasa.gov"
    # uvg_root: "https://uvg.uat.earthdata.nasa.gov"
    dmmt_root: "https://draftmmt.uat.earthdata.nasa.gov"
    gkr_root: "https://gcmd.nasa-impact.net"
  sit:
    urs_root: "https://sit.urs.earthdata.nasa.gov"
    echo_root: "https://cmr.sit.earthdata.nasa.gov/legacy-services"
    cmr_root: "https://cmr.sit.earthdata.nasa.gov"
    edsc_root: "https://search.sit.earthdata.nasa.gov"
    launchpad_root: "https://apps.launchpad.nasa.gov"
    launchpad_sbx_root: "https://apps.launchpad-sbx.nasa.gov"
    uvg_root: "https://uvg.sit.earthdata.nasa.gov"
    dmmt_root: "https://draftmmt.sit.earthdata.nasa.gov"
    gkr_root: "https://gkr.sit.earthdatacloud.nasa.gov"
  dit:
    urs_root: "https://uat.urs.earthdata.nasa.gov"
    echo_root: "https://cmr.uat.earthdata.nasa.gov/legacy-services"
    cmr_root: "https://cmr.uat.earthdata.nasa.gov"
    edsc_root: "https://search.uat.earthdata.nasa.gov"
    launchpad_root: "https://apps.launchpad.nasa.gov"
    launchpad_sbx_root: "https://apps.launchpad-sbx.nasa.gov"
    # uvg_root: "https://uvg.sit.earthdata.nasa.gov"
    dmmt_root: "https://draftmmt.uat.earthdata.nasa.gov"
    gkr_root: "https://gcmd.nasa-impact.net"

# Every (MMT, URS) environment pair has a different client id.
urs:
  mmt_proper:
    production:
      "https://urs.earthdata.nasa.gov": "QCuabaWMrGyq0OvCj0X-pg"
    uat:
      "https://uat.urs.earthdata.nasa.gov": "zFb4tV63ET-V6-oRnDKmJg"
    sit:
      "https://sit.urs.earthdata.nasa.gov": "81FEem91NlTQreWv2UgtXQ"
    development:
      "https://sit.urs.earthdata.nasa.gov": "81FEem91NlTQreWv2UgtXQ"
    test:
      "https://sit.urs.earthdata.nasa.gov": "81FEem91NlTQreWv2UgtXQ"
    dit:
      "https://uat.urs.earthdata.nasa.gov": "Gbw3ItT1gJ8LQ8SCLV527w"
  mmt_proposal_mode:
    # TODO: Draft MMT production and uat have not yet been registered with URS
    # when they have, we will need to update these client ids
    production:
      "https://urs.earthdata.nasa.gov": "9HnEWMMXk5nXOPaxxRg7bA"
    uat:
      "https://uat.urs.earthdata.nasa.gov": "neKOIkHeOyvhjKWZmzl_fQ"
    sit:
      "https://sit.urs.earthdata.nasa.gov": "K1EF5n6rbUzoEi_1SFOLQg"
    development:
      "https://sit.urs.earthdata.nasa.gov": "K1EF5n6rbUzoEi_1SFOLQg"
    test:
      "https://sit.urs.earthdata.nasa.gov": "K1EF5n6rbUzoEi_1SFOLQg"
    dit:
      "https://uat.urs.earthdata.nasa.gov": "Gbw3ItT1gJ8LQ8SCLV527w"

echo_soap:
  services:
    authentication:
      wsdl: "echo-wsdl/v10/AuthenticationService.wsdl"
      path: "echo-v10/AuthenticationServicePortImpl"
    provider:
      wsdl: "echo-wsdl/v10/ProviderService.wsdl"
      path: "echo-v10/ProviderServicePortImpl"
    data_management:
      wsdl: "echo-wsdl/v10/DataManagementService.wsdl"
      path: "echo-v10/DataManagementServicePortImpl"
    service_management:
      wsdl: "echo-wsdl/v10/ServiceManagementService.wsdl"
      path: "echo-v10/ServiceManagementServicePortImpl"
    order_management:
      wsdl: "echo-wsdl/v10/OrderManagementService.wsdl"
      path: "echo-v10/OrderManagementServicePortImpl"
    order_processing:
      wsdl: "echo-wsdl/v10/OrderProcessingService.wsdl"
      path: "echo-v10/OrderProcessingServicePortImpl"
    user_service:
      wsdl: "echo-wsdl/v10/UserService.wsdl"
      path: "echo-v10/UserServicePortImpl"
