---
http_interactions:
  - request:
      method: get
      uri: https://cmr.sit.earthdata.nasa.gov/configuration/tea/provider/POCLOUD
      body:
        encoding: US-ASCII
        string: ''
      headers:
        User-Agent:
          - Faraday v0.8.11
        Client-Id:
          - MMT
        Echo-ClientId:
          - MMT
    response:
      status:
        code: 200
        message:
      headers:
        x-secret-message:
          - HELLO
        strict-transport-security:
          - max-age=31536000;, max-age=31536000; includeSubDomains;
        cache-control:
          - max-age=0, private, must-revalidate
        content-type:
          - text/html; charset=utf-8
        date:
          - Mon, 13 Mar 2017 17:59:02 GMT
        etag:
          - '"513ad7cbd2bac0dc065051e20f181901"'
        server:
          - nginx/1.10.2
        x-runtime:
          - '0.200000'
        x-ua-compatible:
          - IE=Edge,chrome=1
        content-length:
          - '744'
        connection:
          - close
      body:
        encoding: UTF-8
        string: 'tea configuration'
      http_version:
    recorded_at: Mon, 13 Mar 2017 17:58:02 GMT
recorded_with: VCR 3.0.1